#
# AET Docker
#
# Copyright (C) 2018 Maciej Laskowski
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

FROM maven:3.8.4-jdk-8
RUN apt-get update \
    && apt-get install git unzip tzdata \
    && update-ca-certificates

RUN mkdir -p ~/.ssh/ && ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts \
 && git clone git://github.com/ops4j/org.ops4j.pax.logging.git pax\
 && cd pax \
 && git checkout tags/logging-1.10.1 -b logging-1.10.1-aet \
 && git status

WORKDIR /pax
# RUN mvn clean install -DskipTests

CMD tail -f /dev/null
# docker build -t hackkarafpax -f Dockerfile-hackkarafpax .
# docker exec -it 98472983472 /bin/bash
#
# mvn clean install
