#
# AET Docker
#
# Copyright (C) 2018 Maciej Laskowski
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

FROM maven:3.8.4-jdk-8
RUN apt-get update \
    && apt-get install git unzip tzdata \
    && update-ca-certificates

# Clone BMP Proxy fork with log4j fix, see https://github.com/lightbody/browsermob-proxy/pull/891
RUN mkdir -p ~/.ssh/ && ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts \
 && git clone git://github.com/apache/karaf.git \
 && cd karaf \
 && git checkout tags/karaf-4.2.0 -b karaf-4.2.0-aet \
 && git status

WORKDIR /karaf

RUN sed -i 's/http/https/g' assemblies/features/base/pom.xml \
 && sed -i 's/1.10.1/1.11.14/g' pom.xml

CMD tail -f /dev/null

# > cat pom.xml | grep 1.11
#         <pax.logging.version>1.11.14</pax.logging.version>
# > mvn clean install -DskipTests -Pfastinstall
# ...
# [INFO] ------------------------------------------------------------------------
# [INFO] BUILD SUCCESS
# [INFO] ------------------------------------------------------------------------
# [INFO] Total time:  08:58 min
# [INFO] Finished at: 2022-02-09T13:13:52Z
# [INFO] ------------------------------------------------------------------------


# karaf/assemblies/apache-karaf/target/apache-karaf-4.2.0.zip