
FROM openjdk:8-alpine
# Set the env params
ENV JAVA_MAX_MEM 1024m
ENV JAVA_MIN_MEM 256m
ENV KARAF_EXEC exec

# Set the build params
ARG KARAF_VERSION="4.2.0"
ARG KARAF_DOWNLOAD_SHA512="431ca85af2cc230ffb6ab996cb12034a940e21ac4d03ac04936a4ab5e902c7a4e767f06ad32796d250a30ce090aa1b39d927d84955400803e3ee4e3f5116fea4"
ARG KARAF_DOWNLOAD_URL="http://archive.apache.org/dist/karaf/${KARAF_VERSION}/apache-karaf-${KARAF_VERSION}.tar.gz"

RUN apk add --update bash tar jq curl tree && rm -rf /var/cache/apk/*

RUN curl -fSL -o /tmp/apache-karaf.tar.gz ${KARAF_DOWNLOAD_URL} \
    && echo "${KARAF_DOWNLOAD_SHA512}  /tmp/apache-karaf.tar.gz" | sha512sum -c - \
    && mkdir -p /opt/karaf \
    && tar --strip-components=1 -C /opt/karaf -xzf /tmp/apache-karaf.tar.gz \
    && rm /tmp/apache-karaf.tar.gz \
    && mkdir -p /opt/karaf/data /opt/karaf/data/log \
    && echo org.ops4j.pax.url.mvn.defaultRepositories = file:///opt/maven/repository@id=local.app@snapshots  >> /opt/karaf/etc/org.ops4j.pax.url.mvn.cfg \
    && sed -i "s+http://+https://+g" /opt/karaf/etc/org.ops4j.pax.url.mvn.cfg \
    && echo org.ops4j.pax.url.mvn.localRepository = file:///home/karaf/.m2/repository  >> /opt/karaf/etc/org.ops4j.pax.url.mvn.cfg

# Clean old pax-logging
RUN rm -rf /opt/karaf/system/org/ops4j/pax/logging/pax-logging-api/1.10.1 \
 && rm -rf /opt/karaf/system/org/ops4j/pax/logging/pax-logging-log4j2/1.10.1 \
 && rm -rf /opt/karaf/system/org/ops4j/pax/logging/pax-logging-logback/1.10.1

# Replace framework features file
COPY bundles/pax-logging-api-1.10.10.jar /opt/karaf/system/org/ops4j/pax/logging/pax-logging-api/1.10.10
COPY bundles/pax-logging-log4j2-1.10.10.jar /opt/karaf/system/org/ops4j/pax/logging/pax-logging-log4j2/1.10.10
COPY bundles/pax-logging-logback-1.10.10.jar /opt/karaf/system/org/ops4j/pax/logging/pax-logging-logback/1.10.10

# Replace all occurences of pax-logging 1.10.1 with 1.10.10
RUN sed -i 's/1.10.1/1.10.10/g' /opt/karaf/bin/instance \
 && sed -i 's/1.10.1/1.10.10/g' /opt/karaf/bin/shell \
 && sed -i 's/1.10.1/1.10.10/g' /opt/karaf/etc/startup.properties \
 && sed -i 's/1.10.1/1.10.10/g' /opt/karaf/system/org/apache/karaf/features/framework/4.2.0/framework-4.2.0-features.xml

# COPY provision-karaf.sh /tmp/provision-karaf.sh
# RUN chmod a+x /tmp/provision-karaf.sh && sync && /tmp/provision-karaf.sh 102

ENV KARAF_USER karaf
ENV KARAF_UID 8181
ENV JAVA_MAX_MEM 1024m
ENV JAVA_MIN_MEM 256m
ENV KARAF_EXEC exec

RUN addgroup -S -g ${KARAF_UID} ${KARAF_USER}; \
    adduser -S -u ${KARAF_UID} -g ${KARAF_USER} ${KARAF_USER}

RUN chown -R ${KARAF_USER}.${KARAF_USER} /opt/karaf

COPY entrypoint.sh /opt/karaf/entrypoint.sh
RUN chmod a+x /opt/karaf/entrypoint.sh && chown -R ${KARAF_USER}.${KARAF_USER} /opt/karaf/entrypoint.sh

EXPOSE 1099 8101 8181 44444

USER ${KARAF_USER}

ENTRYPOINT ["sh", "/opt/karaf/entrypoint.sh"]
CMD ["run"]

# Running karaf
# Feb 09, 2022 11:28:43 AM org.apache.karaf.main.Main launch
# INFO: Installing and starting initial bundles
# Error installing bundle listed in startup.properties with url: mvn:org.ops4j.pax.logging/pax-logging-api/1.10.10 and startlevel: 8
# Feb 09, 2022 11:28:43 AM org.apache.karaf.main.Main main
# SEVERE: Could not launch framework
# java.lang.RuntimeException: Error installing bundle listed in startup.properties with url: mvn:org.ops4j.pax.logging/pax-logging-api/1.10.10 and startlevel: 8
# 	at org.apache.karaf.main.Main.installAndStartBundles(Main.java:549)
# 	at org.apache.karaf.main.Main.launch(Main.java:272)
# 	at org.apache.karaf.main.Main.main(Main.java:178)
# Caused by: java.lang.RuntimeException: Could not resolve mvn:org.ops4j.pax.logging/pax-logging-api/1.10.10
# 	at org.apache.karaf.main.util.SimpleMavenResolver.resolve(SimpleMavenResolver.java:59)
# 	at org.apache.karaf.main.Main.installAndStartBundles(Main.java:541)
# 	... 2 more