name: Release AET Karaf image

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: 'Version to release'
        
jobs:
  release-karaf:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push Karaf image
        uses: docker/build-push-action@v4
        with:
          context: karaf
          push: true
          # platforms: linux/amd64,linux/arm64
          platforms: linux/arm64
          tags: malaskowski/aet_karaf:${{ github.event.inputs.version }}