name: Release AET images

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: 'Version to release'
        
jobs:
  release-aet-images:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push Client image
        uses: docker/build-push-action@v4
        with:
          context: client
          push: true
          platforms: linux/amd64,linux/arm64
          tags: malaskowski/aet_client:${{ github.event.inputs.version }},malaskowski/aet_client:latest
      -
        name: Build and push ActiveMQ image
        uses: docker/build-push-action@v4
        with:
          context: activemq
          push: true
          platforms: linux/amd64,linux/arm64
          tags: malaskowski/aet_activemq:${{ github.event.inputs.version }}
      -
        name: Build and push Browsermob image
        uses: docker/build-push-action@v4
        with:
          context: browsermob
          push: true
          platforms: linux/amd64,linux/arm64
          tags: malaskowski/aet_browsermob:${{ github.event.inputs.version }}
      -
        name: Build and push Report image
        uses: docker/build-push-action@v4
        with:
          context: report
          push: true
          platforms: linux/amd64,linux/arm64
          tags: malaskowski/aet_report:${{ github.event.inputs.version }}
      -
        name: Build and push Karaf image
        uses: docker/build-push-action@v4
        with:
          context: karaf
          push: true
          platforms: linux/amd64,linux/arm64
          tags: malaskowski/aet_karaf:${{ github.event.inputs.version }}